{
 "title": "My First Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Targets",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}} - {{instance}}" }
   ]
  },
  {
   "title": "Network Traffic Received",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])"
    }
   ]
  },
  {
   "title": "Kernel Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_uname_info" }
   ]
  },
  {
   "title": "Prometheus Time Series",
   "type": "stat",
   "description": "Prometheus Time Series",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  }
 ]
}