{
 "title": "Chapter 13 - Introduction to PromQL",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Aggregation Basics - Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SUM node_filesystem_size_bytes 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum without(device, fstype, mountpoint)(node_filesystem_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUM node_filesystem_size_bytes 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum without(device, fstype, mountpoint, instance)(node_filesystem_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAX node_filesystem_size_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max without(device, fstype, mountpoint)(node_filesystem_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG process_open_fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg without(instance, job)(process_open_fds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aggregation Basics - Counter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "node_network_receive_bytes_total 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "node_network_receive_bytes_total 2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum without(device)(rate(node_network_receive_bytes_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "node_network_receive_bytes_total 3",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sum without(instance)(rate(node_network_receive_bytes_total{device=\"eth0\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Aggregation Basics - Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "SUM prometheus_http_response_size_bytes_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum without(handler)(rate(prometheus_http_response_size_bytes_count[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SUM prometheus_http_response_size_bytes_sum",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum without(handler)(rate(prometheus_http_response_size_bytes_sum[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AVG prometheus_http_response_size_bytes 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum without(handler)(rate(prometheus_http_response_size_bytes_sum[5m]))\n/\nsum without(handler)(rate(prometheus_http_response_size_bytes_count[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AVG prometheus_http_response_size_bytes 2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum without(instance)(\n    sum without(handler)(rate(prometheus_http_response_size_bytes_sum[5m]))\n  )\n/\n  sum without(instance)(\n    sum without(handler)(rate(prometheus_http_response_size_bytes_count[5m]))\n  )\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Aggregation Basics - Histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "P90 prometheus_tsdb_compaction_duration_seconds_bucket 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.90,\n    rate(prometheus_tsdb_compaction_duration_seconds_bucket[1d]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P90 prometheus_tsdb_compaction_duration_seconds_bucket 2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.90,\n  sum without(instance)(rate(prometheus_tsdb_compaction_duration_seconds_bucket[1d])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AVG prometheus_tsdb_compaction_duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum without(instance)(rate(prometheus_tsdb_compaction_duration_sum[1d]))\n/\nsum without(instance)(rate(prometheus_tsdb_compaction_duration_count[1d]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Selectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Matchers - node_filesystem_size_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=\"node\",mountpoint=~\"/var/lib/mount-services-cache/.*\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Range Vector - process_cpu_seconds_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Subqueries - prometheus_http_requests_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "max_over_time( rate(prometheus_http_requests_total[5m])[30m:1m] )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Subqueries - prometheus_http_requests_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "max_over_time( rate(prometheus_http_requests_total[5m])[30m:1m] )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Selectors - Offset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "process_resident_memory_bytes 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"node\"} offset 1h",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}