{
 "title": "Coin App Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Business Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Coin Balance per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "puar_golang_coin_balance", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Coin Balance per Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "puar_golang_coin_balance", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Coins Saving Rate per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "rate(puar_golang_transaction_coin_total{path=\"/v1/save\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Coins Spending Rate per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "-rate(puar_golang_transaction_coin_total{path=\"/v1/spend\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Save Request Success Rate per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - rate(puar_golang_http_request_error{path=\"/v1/save\"}[1m]) / rate(puar_golang_http_request_total{path=\"/v1/save\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Spend Request Success Rate per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - rate(puar_golang_http_request_error{path=\"/v1/spend\"}[1m]) / rate(puar_golang_http_request_total{path=\"/v1/spend\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}