version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - 9090:9090
  golang-app:
    build: ./golang-app
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    networks:
      - localprom
  python-request-generator:
    build: ./python-request-generator
    networks:
      - localprom
networks:
  localprom:
    driver: bridge
