global:
  scrape_interval: 10s
scrape_configs:
 - job_name: ulises-prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: golang-app
   static_configs:
    - targets:
       - golang-app:8080
