{
 "title": "Chapter 14 - Aggregation Operators",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Grouping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "without - node_filesystem_size_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(fstype, mountpoint)(node_filesystem_size_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "by - node_filesystem_size_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(job, instance, device)(node_filesystem_size_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "by - Time Series Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sort_desc(count by(__name__)({__name__=~\".+\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "by - Kernel Version",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "count by(release)(node_uname_info)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Operators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "sum - Total Node Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(fstype, mountpoint, device)(node_filesystem_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sum -Total Disk Read (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(device)(rate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "count -Total Disk Devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count without(device)(node_disk_read_bytes_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "count -Total CPUs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count without(cpu)(count without (mode)(node_cpu_seconds_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "avg - CPU utilization (%) per mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu)(rate(node_cpu_seconds_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "group -Total Filesystems",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (instance)(\n  group by (fstype,instance) (node_filesystem_files)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "max and min- Biggest and Smallest Filesystems",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max without(device, fstype, mountpoint)(node_filesystem_size_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "min without(device, fstype, mountpoint)(node_filesystem_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "topk and bottomk- Biggest and Smallest Filesystems",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk without(device, fstype, mountpoint)(2, node_filesystem_size_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "bottomk without(device, fstype, mountpoint)(2, node_filesystem_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "quantile - P90 CPU time in system mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile without(cpu)(0.9, rate(node_cpu_seconds_total{mode=\"system\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "quantile - Job CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg without(instance)(rate(process_cpu_seconds_total[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile without(instance)(0.25, rate(process_cpu_seconds_total[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile without(instance)(0.5, rate(process_cpu_seconds_total[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile without(instance)(0.75, rate(process_cpu_seconds_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "count_values - Disks in node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_values without(instance)(\n  \"devices\",\n  count without(device) (node_disk_io_now)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}