{
 "title": "Chapter 15 - Binary Operators",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Scalars - Arithmetics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Division - process_resident_memory_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes / 1024",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Modulo in Floating point - 5 % 1.5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "5 % 1.5", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Subtraction - process_resident_memory_bytes (1GB - memory)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "1e9 - process_resident_memory_bytes",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Scalars - Comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Greater than - process_open_fds > 10",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      { "expr": "process_open_fds > 10", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Bool Modifier - process_open_fds > 10",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(instance)(process_open_fds > bool 10)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bool Modifier - node_disk_io_now > 4",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without(instance)(\n  count without(device)(node_disk_io_now) > bool 4\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Vector Matching - One to One",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Division - process_open_fds (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_open_fds / process_max_fds",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Division with ignoring - iddle node_cpu_seconds_total (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum without(cpu)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))\n/ ignoring(mode)\n  sum without(mode, cpu)(rate(node_cpu_seconds_total[5m]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Division with on - iddle node_cpu_seconds_total (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(instance, job)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))\n/ on(instance, job)\n  sum by(instance, job)(rate(node_cpu_seconds_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Boolean operators - process_open_fds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_open_fds > (process_max_fds * 0.000001)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Boolean operators - process_max_fds (* 0.000001)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(process_max_fds * 0.000001) < process_open_fds",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Vector Matching - Many to One",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Group Left - node_cpu_seconds_total per mode (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum without(cpu)(rate(node_cpu_seconds_total[5m]))\n/ ignoring(mode) group_left\n  sum without(mode, cpu)(rate(node_cpu_seconds_total[5m]))",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Group Left - Prometheus version",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "up\n* on(instance) group_left(version)\n  prometheus_build_info",
       "legendFormat": "{{version}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Vector Matching - Many to Many",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  },
  {
   "title": "OR - node_hwmon_temp_celsius (if available)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius\nor\n  (up{job=\"node\"} == 1) * 0",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "UNLESS - node_hwmon_temp_celsius (If missing)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "up{job=\"node\"} == 1\nunless\n  node_hwmon_temp_celsius",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "AND - prometheus_http_request_duration_seconds average > 10ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\nrate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\"}[5m])\n    /\n      rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\"}[5m])\n  ) > 0.01\nand\n  rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\"}[5m]) > 0.1",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}