{
 "title": "Chapter 16 - Functions",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Changing Type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vector - 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      { "expr": "vector(1)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Vector - CPU-0 Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\", cpu=\"0\"}[1m])) or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scalar - ln(10)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "scalar(ln(vector(10)))", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Scalar - Year that Jobs started",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "year(process_start_time_seconds) == scalar(year())",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Math",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Abs - process_open_fds * -1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      { "expr": "abs(-process_open_fds)", "legendFormat": "__auto" },
      { "expr": "-process_open_fds", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "log2, log10 and ln",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      { "expr": "ln(vector(10))", "legendFormat": "__auto" },
      { "expr": "log2(vector(10))", "legendFormat": "__auto" },
      { "expr": "log10(vector(10))", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "exp",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      { "expr": "exp(vector(1))", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "sqrt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      { "expr": "sqrt(vector(100))", "legendFormat": "__auto" },
      { "expr": "vector(100) ^ (1/3)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "cei, floor and round",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      { "expr": "ceil(vector(0.1))", "legendFormat": "__auto" },
      { "expr": "floor(vector(0.1))", "legendFormat": "__auto" },
      { "expr": "round(vector(2.1))", "legendFormat": "__auto" },
      { "expr": "round(vector(2.6))", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "clamp, clamp_max, clamp_min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "clamp_min(process_open_fds, 10)",
       "legendFormat": "clamp_min({{job}}, 10)"
      },
      {
       "expr": "clamp_max(process_open_fds, 15)",
       "legendFormat": "clamp_max({{job}}, 15)"
      },
      {
       "expr": "clamp(process_open_fds, 12, 14)",
       "legendFormat": "clamp({{job}}, 12, 14)"
      }
     ]
    },
    {
     "title": "sgn",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      { "expr": "sgn(vector(100))", "legendFormat": "__auto" },
      { "expr": "sgn(vector(-100))", "legendFormat": "__auto" },
      { "expr": "sgn(vector(0))", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    { "expr": "time()", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    { "expr": "minute()", "legendFormat": "__auto" },
    {
     "expr": "minute(process_start_time_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "timestamp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "timestamp(up)", "legendFormat": "__auto" }
   ]
  }
 ]
}