global:
  scrape_interval: 10s
scrape_configs:
 - job_name: ulises-prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: golang-labels-app-v1
   static_configs:
    - targets:
       - golang-labels-app-v1:8080
 - job_name: golang-labels-app-v2
   static_configs:
    - targets:
       - golang-labels-app-v2:8081
